name: EFI_INSTALL_CONFIGURATION_TABLE
reference_link: "https://uefi.org/specs/UEFI/2.11/07_Services_Boot_Services.html#efi-boot-services-installconfigurationtable"
uefi_version: 2.11
size: NATIVE_WORD_SIZE
